# Generated by Django 2.2.6 on 2019-12-03 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recruit_name', models.CharField(max_length=100)),
                ('answers', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Sith',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('shadowhand_used', models.PositiveSmallIntegerField(default=0)),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.Planet', to_field='name')),
            ],
        ),
        migrations.CreateModel(
            name='ShadowHand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_key', models.CharField(max_length=120)),
                ('question_list', models.ManyToManyField(to='recruit.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Recruit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('age', models.PositiveSmallIntegerField(default=0)),
                ('email', models.EmailField(max_length=100)),
                ('got_shadowhand', models.BooleanField(default=False)),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.Planet', to_field='name')),
            ],
        ),
    ]
