# Generated by Django 2.2.6 on 2019-10-19 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sith',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('planet', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ShadowHand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_key', models.TextField(max_length=100)),
                ('question_list', models.ManyToManyField(to='recruit.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Recruit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('age', models.PositiveSmallIntegerField(default=0)),
                ('email', models.TextField(max_length=100)),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='recruit.Planet', to_field='slug')),
            ],
        ),
    ]
