# Generated by Django 2.2.6 on 2019-10-19 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='planet',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='planet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='recruit.Planet', to_field='name'),
        ),
        migrations.AlterField(
            model_name='shadowhand',
            name='order_key',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='sith',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sith',
            name='planet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='recruit.Planet', to_field='name'),
        ),
    ]
