# Generated by Django 2.2.6 on 2019-10-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0002_auto_20191020_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruit',
            name='got_shadowhand',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
