# Generated by Django 2.2.6 on 2019-10-22 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0004_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='sith',
            name='shadowhand_used',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
